# Generated by Django 4.0.8 on 2023-08-07 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operationApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='complete',
        ),
        migrations.AddField(
            model_name='todo',
            name='content',
            field=models.CharField(default='This is default', max_length=200),
        ),
        migrations.AddField(
            model_name='todo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
